# Generated by Django 4.2.3 on 2023-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_user_id',
            field=models.CharField(default='NO', max_length=255),
            preserve_default=False,
        ),
    ]
